# Generated by Django 2.2.5 on 2019-09-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categotry',
            new_name='name',
        ),
    ]
